### PR TITLE
Fix silicon not appearing in recipe book

### LINKED ISSUE #23: Silicon lump crafting recipe doesn't appear in recipe book
The recipe to craft silicon lumps does not appear in the recipe book. You can still craft silicon lumps despite this. This occurs both with and without `mesecons_materials` installed.

No other recipe has this issue.

### PR DESCRIPTION
**Pull request by FlitPix**
Fixes #23.

### CODE REVIEW

**Review by wsor4035 — CHANGES_REQUESTED** [review]
seems that silicon should be removed from the crafting items compat tables, and where it is used replaced with the `basic_materials:silicon` itemstring rather than piecemealing it. also seem to have added an unrelated whitespace change

**Comment by FlitPix** [comment]
> also seem to have added an unrelated whitespace change

That's just a newline at the end of the file that wasn't there before. Should I remove it? Figured it was fine to add

**Comment by S-S-X** [comment]
> Should I remove it?

As it is only change in that file and newline is not needed yes it would be better to remove it.

**Review by wsor4035 — APPROVED** [review]
seems legit. i have no objections

**Pull request merged**
