### PR TITLE
Better compatibility with Hades Revisited.

### PR DESCRIPTION
**Pull request by sfence**

### CODE REVIEW

**Comment by wsor4035** [comment]
not sure why the first three commits are from the this repo. anyways the code seems to work, however a potential suggestion? not sure myself, but I think it might be better instead of multiple if statements for each node that gets aliased instead of registered in hades, that it would be better to have one if statement and then use `minetest.register_alias_force(alias, original_name)`. The advantages I see in such an approach are that they are all grouped together, easy for troubleshooting if something goes wrong, and cleaner code

**Comment by sfence** [comment]
It is probably because I started from the hades branch or because I merged it with master to go around some bugs fixed in master branch.
After merge, it will probably require merging mt-mods:hades into mt-mods:master.

**Review by wsor4035 — APPROVED** [review]

**Comment by wsor4035** [comment]
SX has the comment "formatting spaces vs. tabs btw." once that is fixed ill merge this into hades branch and then into master since this wasnt PR'd to master

apologies on the wait

**Comment by sfence** [comment]
I am sorry. I have checked only the beginning of crafts.lua files and see that spaces are used here like indent. So I continued with it.
Now all indent spaces should be replaced by tabs in crafts.lua and craftitems.lu files, including spaces from previous commits.

**Pull request merged**
