### PR TITLE
graceful user error fallback

### PR DESCRIPTION
**Pull request by wsor4035**
what the title says

### CODE REVIEW

**Comment by S-S-X** [comment]
I don't think this is really useful in any way, it just hides actual error messages and stack traces.

Unless if there's actual fallback mechanism available that I'm not aware of?

**Comment by wsor4035** [comment]
it allows the mod to keep running if sound isnt found.

**Comment by S-S-X** [comment]
> it allows the mod to keep running if sound isnt found.

It is not checking for sounds at all but for sound_api and just ignores sounds if sound_api cannot be loaded.
Also error says it did not find sounds while it actually did not find sound_api, this hides a lot of  useful information which is available with stack trace.

**Comment by wsor4035** [comment]
> It is not checking for sounds at all but for sound_api and just ignores sounds if sound_api cannot be loaded. Also error says it did not find sounds while it actually did not find sound_api, this hides a lot of useful information which is available with stack trace.

change the error message if you like. this is to address complaints of the mod crashing because users dont have the submodule.  
[EDIT]: it isnt a error, its a warning that it wasnt found. feel free to change the log level if desired

**Comment by wsor4035** [comment]
@S-S-X https://github.com/mt-mods/basic_materials/pull/5/commits/19c690d7e92b0b957f8e33280d741413d758fcf6 improved warning message

**Comment by wsor4035** [comment]
could change the log level to error so that it dumps the message into a players chat on start up if in singleplayer

**Comment by SwissalpS** [comment]
It is an error, when an extra install step is requiered for something to work as expected and as it used to.

**Comment by wsor4035** [comment]
> It is an error, when an extra install step is requiered for something to work as expected and as it used to.

....so this means....what exactly?
you want the log level to be error?
you want to just leave it as it is currently and let the mod error if sound_api isnt found?
some other thing?

**Comment by S-S-X** [comment]
> @S-S-X [19c690d](https://github.com/mt-mods/basic_materials/commit/19c690d7e92b0b957f8e33280d741413d758fcf6) improved warning message

Link to git documentation is not really useful in my opinion. If linking to anything it should be linking to basic_materials documentation "how to install mod" section.

> you want to just leave it as it is currently and let the mod error if sound_api isnt found?

I would recommend this to make it clear that sound_api is providing core functionality.
With error error message clearly telling that sound_api is not there (like it is currently) and possibly link to basic_materials installation documentation (instead of git documentation).

Possibly add configuration option to skip sound_api (mention this in error message), this provides easy way to skip it while still makes it very clear that mod is crippled and is not delivering all functionality.
With this I am assuming that sound_api attempts to work as primary source for sounds and is actually important part of mod that is utilizing it.

If sound_api is meant to be completely optional and not that important part of but secondary extension and primary way would be to provide sounds through mod then explicitly mention that in sound_api documentation and provide "how to use" documentation for sound_api with fallback instructions.

**Comment by wsor4035** [comment]
@S-S-X so to summarize your more in favor of letting the mod crash, but providing a custom error message with the traceback? if so ill close this and make a PR for that

**Comment by S-S-X** [comment]
> 

Yes if it is important part, possibly providing condifguration option to bypass error if someone really needs that.
To clarify: this is to make it very clear that mod will be crippled not providing all intended functionality if sound_api is missing.

No if it is not important part, we can also restore fallback sounds that were removed in refactoring.

**Comment by wsor4035** [comment]
converted to draft till as per sx request i will add a custom error message with the stack traceback and a configuration option to load this without sound

**Pull request closed without merging**
