### PR TITLE
Add aluminum bar, strip and wire, gold strip and stainless steel bar …

### PR DESCRIPTION
**Pull request by sfence**
…and strip.

Textures made by me (edited original ones). The license is the same.

### CODE REVIEW

**Comment by wsor4035** [comment]
why is there an added optional depends on aloz ?
edit: turns out its a mod by runs https://forum.minetest.net/viewtopic.php?t=27213 - https://github.com/runsy/aloz/

**Comment by wsor4035** [comment]
additionally, could these potentially use hardware coloring? - it does make sense to have variations of all the metals rather than the current piecemeal

**Comment by S-S-X** [comment]
Craft registration checks for materials but craft item registrations do not, would it be good to add that check for `materials["aluminum_ingot"]` and possibly extend to other materials later?
Or is there a good reason to register items without materials and recipes?

**Comment by S-S-X** [comment]
@wsor4035 I think you replied with opinion but could you elaborate what emoji means?

**Comment by wsor4035** [comment]
because your comment is a 🤦 moment with how mods generally do things in minetest. usually mods at least register there items even if they dont have a craft. traditionally mods usually check to say for example `if minetest.get_modpath("modname")` then use its feature set, *like this exact mod does* rather than specifically checking for every item, etc.

additionally, say we did go with this odd idea of yours that goes contrary to how most mods work, say to get around this, mod b, c, d, do `minetest.register_node(":basic_materials:item")` and add a craft for it, and now mod e wants to use that item. they now have to check for that item, before registering it themselves, and due to how minetest mod loader works, unless they have all the others as opt deps, it may not get loaded before them. doing it the normal way of registering the item, mod e just registers its crafting recipe and moves on

**Comment by sfence** [comment]
> additionally, could these potentially use hardware coloring? - it does make sense to have variations of all the metals rather than the current piecemeal

Potentially yes. but I am only an item adder, So I think, it is on mod maintainers to think about it and realize it.

**Comment by wsor4035** [comment]
> > additionally, could these potentially use hardware coloring? - it does make sense to have variations of all the metals rather than the current piecemeal
> 
> Potentially yes. but I am only an item adder, So I think, it is on mod maintainers to think about it and realize it.

i know it can be done, my concern lies with backwards compat of other mods using the items in recipes - i do have an idea on how to do it, but it might not be the prettiest.....

**Comment by wsor4035** [comment]
if no objections, i will give hardware coloring backwards compat a try. and pr/post a diff here for sfence

**Comment by sfence** [comment]
> if no objections, i will give hardware coloring backwards compat a try. and pr/post a diff here for sfence

Maybe, it will be better to be done it like a separate pull request?

**Comment by wsor4035** [comment]
> > if no objections, i will give hardware coloring backwards compat a try. and pr/post a diff here for sfence
> 
> Maybe, it will be better to be done it like a separate pull request?

i mean, yeah, if that the decided path, would go with that one so dont have to do backwards compat for things introduced here as well 🙃

**Comment by wsor4035** [comment]
investigated the hardware coloring option, making it work is fine, however backwards compat is doable, it would just suck and be full of lot of hacks. (if your really curious, i can explain in the discord/irc channel some time). for that reason, i think that at this time its not worth using hardware coloring here....at this time.

**Review by wsor4035 — APPROVED** [review]
looks good

**Comment by wsor4035** [comment]
leaving this open for a bit to give others a chance to comment due to the preceding conversation. else i will merge after a bit

**Pull request merged**
